### ISSUE TITLE
Вопрос: как бы вы изменили раскладку для эргономичной клавиатуры?

### ISSUE THREAD

**Issue by kvaDrug** [mshkrebtan/diktor#1]
Представьте, что у вас есть эргономичная клавиатура вроде [dactyl-manuform](https://github.com/abstracthat/dactyl-manuform). Она симметричная (под левым мезинцем можно поставить столько же букв, сколько под правым), функциональные клавиши вроде Shift и Tab можно перенести в кластер большого пальца. Как бы вы передвинули несколько кнопок, с учетом этого. В частности буква Ë сильно мешает: если оставить её там, где она есть, пришлось бы делать 7 столбцов клавиш справа. Может стоит вынести ее на большой палец или куда-то вниз под средний или безымянный, вместо клавиши  alt? А что на счет Й и Щ? В случае клавиатуры типа dactyl, я бы все эти "выпирающие" справа буквы (Ë, Щ, Й, Ш) перенес бы под средний и безымянный пальцы, хотя тогда пришлось бы прыгать через 2 ряда. Ну или хотя бы сбалансировал бы нагрузку, поставив пару букв под левый мизинец. Очень интересно ваше мнение по этому поводу. 

П.С. При этом надо еще учитывать наличие английской раскладки на той же клавиатуры. Клавиши типа Del не должны перемещаться при переключении языка.

**Comment by mshkrebtan** [comment]
Очень интересный вопрос. Сам я эргономичными клавиатурами не пользуюсь, пока меня устраивает HHKB, поэтому чего-то конкретного подсказать не могу.

В целом же я бы смотрел на [_typing effort_](http://mkweb.bcgsc.ca/carpalx/?typing_effort) (эффективность набора?) раскладки с учётом конкретно вашей сборки Dactyl. Опять же, показатели эффективности могут различаться в зависимости от _typing effort model_: https://habr.com/ru/post/210826/.

Если смотреть на [частотность букв русского языка](https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C), буквы ё, ъ, щ, ш, й имеют одни из самых низких рангов, и, по-моему, их можно расположить достаточно произвольно на разных клавиатурах (посмотрите на расположение ё в [ЙЦУКЕН и других русских раскладках](https://ru.wikipedia.org/wiki/%D0%99%D0%A6%D0%A3%D0%9A%D0%95%D0%9D#%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D1%8B_%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%BA)). Букву ё с самым низким рангом можно вообще убрать под `Option` + `е`, по аналогии с твёрдым знаком в моей версии «Диктора» или эсцетом ß (`Option` + `s`) на раскладках US International или Colemak.

@strech, подскажешь что-нибудь, как собиратель Dactyl и прочих split-ов?

**Comment by sprainbrains** [comment]
> Очень интересный вопрос. Сам я эргономичными клавиатурами не пользуюсь, пока меня устраивает HHKB, поэтому чего-то конкретного подсказать не могу.
> 
> В целом же я бы смотрел на [_typing effort_](http://mkweb.bcgsc.ca/carpalx/?typing_effort) (эффективность набора?) раскладки с учётом конкретно вашей сборки Dactyl. Опять же, показатели эффективности могут различаться в зависимости от _typing effort model_: https://habr.com/ru/post/210826/.
> 
> Если смотреть на [частотность букв русского языка](https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C), буквы ё, ъ, щ, ш, й имеют одни из самых низких рангов, и, по-моему, их можно расположить достаточно произвольно на разных клавиатурах (посмотрите на расположение ё в [ЙЦУКЕН и других русских раскладках](https://ru.wikipedia.org/wiki/%D0%99%D0%A6%D0%A3%D0%9A%D0%95%D0%9D#%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D1%8B_%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%BA)). Букву ё с самым низким рангом можно вообще убрать под `Option` + `е`, по аналогии с твёрдым знаком в моей версии «Диктора» или эсцетом ß (`Option` + `s`) на раскладках US International или Colemak.
> 
> @Strech, подскажешь что-нибудь, как собиратель Dactyl и прочих split-ов?

А планируется ли версия под виндоус?

**Comment by Strech** [comment]
Извините, не заметил мой меншен. @kvaDrug В случае с буквами как ё, щ и другими редко употребляемыми клавишами, лично я пользовался подходом из сплит-клавиатур типа corne, когда ё через отдельный слой может мапиться. Вообще если у вас QMK, ну или ZMK, то у вас очень много вариантов, таких как tap-dance - нажал на е два раза подряд и получил ё, или задержал на е палец и получил ё (забыл название функции), ну и наконец - combo-keys, нажал е + соседнюю букву, получил ё.

В общем в случае кастомных прошивок всё ограничивается вашим желанием и удобством

**Comment by Simon-The-Human** [comment]
> 
> А планируется ли версия под виндоус?

Кастомные клавиатуры работают под управлением собственного софта на собственных же микроконтроллерах. Соответственно, раскладки и прочие настройки содержатся внутри клавиатуры и от операционной системы не зависят.
Хотя, я пока в вопросе - праздный исследователь, а не практик. Если не прав, поправьте меня.
