### ISSUE TITLE
Type Fu's dictionary or layout doesn't work properly

### ISSUE THREAD

**Issue by crumpledmint** [mshkrebtan/diktor#2]
Though layout works perfectly something doesn't work properly in Type Fu: it shows space as mistake
It doesn't show it with other languages so I guess the problem is on tfl or tfd side

![Снимок экрана 2022-02-18 в 13 39 14](https://user-images.githubusercontent.com/95003914/154667098-c0eef368-0c86-478a-8365-be6637fe3c0e.png)

**Comment by mshkrebtan** [comment]
Hi @crumpledmint,

Thank you for your feedback! I'm surprised by that fact that Type Fu has changed from a native MacOS application to a web one. 

Anyway, I have updated the layout file, adding a definition for the space key. You should see no more errors.
